### ISSUE TITLE
Scrollbars Please

### ISSUE THREAD

**Issue by CasioJones** [tangielsky/rpiconfigedit#1]
I have a laptop that only operates at 1366 x 768 , it's all i have to use at the moment. 
This however limits what can be seen even at full screen. 
In the Display part for HDMI i seem to be missing options.
![Clipboard Image](https://user-images.githubusercontent.com/24987895/56213694-70f2f200-6054-11e9-9e60-e9da66c753ff.jpg)

It's not the only one, great work though. 
ThanksChris

**Comment by tangielsky** [comment]
Hello Chris, 
thanks for that, the scrollbars are now implemented.
More HDMI with the next versions.

Thomas
